# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# 5d081333-2c77-414d-b218-632d488b353d
version: "3.8"

services:
  qdrant-vector-db:
    image: qdrant/qdrant
    container_name: qdrant-vector-db
    ports:
      - "6333:6333"
      - "6334:6334"
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: agents
      MONGO_INITDB_ROOT_PASSWORD: agents
    ports:
      - "27017:27017"
  groq-service:
    image: navchetna/groq:latest
    container_name: groq-service
    ports:
      - "5099:8000"
    volumes:
      - "./cache:/root/.cache"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      GROQ_API_KEY: ${GROQ_API_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
  tei-reranking-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: tei-reranking-server
    ports:
      - "6041:80"
    volumes:
      - "${MODEL_CACHE:-./data}:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HF_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
    command: --model-id ${RERANK_MODEL_ID} --auto-truncate
  tei-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: tei-embedding-server
    ports:
      - "6040:80"
    volumes:
      - "${MODEL_CACHE:-./data}:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate
  retriever:
    image: navchetna/railtel-lenovo-retriever:latest
    container_name: retriever-qdrant-server
    depends_on:
      - qdrant-vector-db
    ports:
      - "6045:7000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      QDRANT_HOST: qdrant-vector-db
      QDRANT_PORT: 6333
      # INDEX_NAME: rag-qdrant
      # QDRANT_INDEX_NAME: rag-qdrant
      TEI_EMBEDDING_ENDPOINT: http://tei-embedding-service:80
      LOGFLAG: ${LOGFLAG}
      RETRIEVER_COMPONENT_NAME: "OPEA_RETRIEVER_QDRANT"
    restart: unless-stopped
  dataprep-qdrant-service:
    image: navchetna/railtel-lenovo-dataprep:latest
    container_name: dataprep-qdrant-server
    depends_on:
      - qdrant-vector-db
      - tei-embedding-service
    ports:
      - "6043:5000"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      QDRANT_HOST: qdrant-vector-db
      QDRANT_PORT: 6333
      # QDRANT_INDEX_NAME: rag-qdrant
      # INDEX_NAME: rag-qdrant
      TEI_EMBEDDING_ENDPOINT: http://tei-embedding-service:80
      HF_TOKEN: ${HF_TOKEN}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      DATAPREP_COMPONENT_NAME: "OPEA_DATAPREP_QDRANT"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/v1/health_check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 50
    restart: unless-stopped

networks:
  default:
    driver: bridge
